### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lesce** [ryan-flores/crossover-rails-assessment#1]
Hi Ryan , 
I was researching the crossover ruby on rails position and I've stumbled across your repository
I wanted to ask you how the interview process was and if you've got the job, I've encountered a few negative reviews (calling it a hoax) but not a single positive one .
Hope to hear soon from you

Thanks

**Comment by rfloper** [comment]
Hi Lesce,

  Yes, I've got the job. Crossover is a great company. Your overall experience will depend on how you get along with the client. They work for many clients around the world.

Thanks,
Ryan

**Comment by lesce** [comment]
Thanks for the response Ryan it's very reassuring to hear that, 
I passed the first test and am starting the project evaluation probably next week .
Congratulations on your achievement and have a nice day !
